# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  active_days: 30
  max_jobs_on_homepage: 10
  max_jobs_on_category: 5
  wsdl_defactosf1_url: "http://www.reportingsales.com/DeFactoSF1.asmx?wsdl"
  defactosf1_key: "ab116cc5-1b96-44b2-a161-6734c50960fd"
