<?php

/**
 * PluginJobeetCategoryAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJobeetCategoryAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJobeetCategoryAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJobeetCategoryAffiliate');
    }
}